import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve(import.meta.dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');

const configExample = read('config.example.js');
const app = read('src/app.js');
const atlasApp = read('src/atlas-app.js');
const map = read('src/map.js');
const smoke = read('tests/test.js');
const shareHtml = read('share.html');
const server = read('server/gee_tile_server.mjs');
const cogRenderer = read('execution/render_cog_tile.py');

assert.match(configExample, /IMAGE_PROVIDER:\s*"cog"/, 'config.example.js should default Produced Water to COG imagery');
assert.match(configExample, /COG_TILE_ENDPOINT:\s*"\/api\/cog\/tiles"/, 'config.example.js should document the COG tile endpoint');
assert.match(configExample, /GEE_TILE_ENDPOINT:\s*"\/api\/gee\/tiles"/, 'config.example.js should document the GEE tile endpoint');
assert.match(configExample, /ATLAS_GEE_TILE_ENDPOINT:\s*"\/api\/gee\/tiles"/, 'config.example.js should document the Atlas GEE tile endpoint');
assert.match(configExample, /ATLAS_SENTINEL_CREDIT_GUARD:\s*true/, 'config.example.js should document Atlas Sentinel guard override');
assert.match(configExample, /ATLAS_SENTINEL_LIVE_TILES:\s*false/, 'config.example.js should document Atlas Sentinel live-tile override');
assert.match(configExample, /ATLAS_SENTINEL_MIN_ZOOM:\s*14/, 'config.example.js should document Atlas Sentinel zoom override');
assert.match(app, /IMAGE_PROVIDER:\s*'cog'/, 'internal app config should default Produced Water to COG imagery');
assert.match(app, /COG_TILE_ENDPOINT:\s*'\/api\/cog\/tiles'/, 'internal app config should provide a COG endpoint');
assert.match(app, /SENTINEL_CREDIT_GUARD:\s*true/, 'Sentinel credit guard should be enabled by default');
assert.match(app, /SENTINEL_LIVE_TILES:\s*false/, 'Sentinel live tiles should be disarmed by default');
assert.match(app, /SENTINEL_MIN_ZOOM:\s*14/, 'Sentinel WMS should require a precise default zoom');
assert.match(app, /toggle-sentinel-live/, 'Settings should expose a Sentinel live tile arm switch');
assert.match(app, /sentinel-min-zoom/, 'Settings should expose a Sentinel minimum zoom control');
assert.match(app, /runtimeImageProviderOverride = 'sentinelhub'/, 'Sentinel toolbar switch should route the session to Sentinel Hub');
assert.match(app, /runtimeImageProviderOverride === 'sentinelhub'[\s\S]*runtimeImageProviderOverride = null/, 'Sentinel toolbar switch should restore the default provider when switched off');
assert.match(app, /function isSentinelOnlyShareMode\(\)/, 'app should detect Sentinel-only share mode');
assert.match(app, /function applySentinelOnlyShareConfig\(config\)/, 'app should have a Sentinel-only share config override');
assert.match(app, /config\.IMAGE_PROVIDER = 'sentinelhub'/, 'share mode should force IMAGE_PROVIDER to Sentinel Hub');
assert.match(app, /config\.ALLOW_SENTINEL_FALLBACK = true/, 'share mode should permit the explicit Sentinel route');
assert.match(app, /config\.SENTINEL_CREDIT_GUARD = true/, 'share mode should keep Sentinel credit guard enabled');
assert.match(app, /config\.SENTINEL_LIVE_TILES = true/, 'share mode should keep Sentinel live tiles armed');
assert.match(app, /sentinelOnlyShareMode: isSentinelOnlyShareMode\(\)/, 'provider state should expose share mode');
assert.match(app, /state\.map\.on\('sentinelratelimit'/, 'app should surface Sentinel Hub rate-limit cooldowns');
assert.match(map, /function getSentinelCreditGuardStatus/, 'map layer factory should check the Sentinel credit guard');
assert.match(map, /getSentinelGuardLayer/, 'Sentinel guard should return a local placeholder layer instead of WMS tiles');
assert.match(map, /state\.map\.fire\('sentinelguard'/, 'Sentinel guard should announce blocked WMS rendering');
assert.match(map, /function getRetryAfterMs/, 'Sentinel WMS loader should honor Retry-After cooldowns');
assert.match(map, /state\.map\.fire\('sentinelratelimit'/, 'Sentinel WMS loader should announce 429 cooldowns');
assert.match(map, /tileSize:\s*512/, 'Sentinel WMS tiles should use larger tiles to reduce request count');
assert.match(map, /maxConcurrent:\s*1/, 'Sentinel WMS tiles should avoid bursty parallel requests');
assert.match(app, /const COG_SUPPORTED_INDEX_KEYS = new Set\(\['none', 'tc', 'truecolor', 'true-color', 'pwi', 'hpwi', 'pwoi', 'lbi'\]\)/, 'COG UI should enumerate only renderer-supported COG indexes');
assert.match(app, /const COG_SCREEN_INDEX_KEYS = new Set\(\['hpwi', 'lbi', 'pwoi', 'pwi'\]\)/, 'Screen flow should expose only supported COG demo lenses');
assert.match(app, /function enforceCogTemporalConstraints\(\)/, 'app should guard temporal controls under COG mode');
assert.match(app, /state\.compareType = 'swipe'/, 'COG mode should fall back to swipe compare instead of diff/cumulative');
assert.match(app, /btnDiff[\s\S]*btnCumulative[\s\S]*btn\.disabled = isCog/, 'COG mode should disable nonfunctional diff/cumulative buttons');
assert.match(app, /getProviderReadyBookmarkIndices\(spill\)/, 'bookmark chips should be filtered by active provider support');
assert.match(app, /if \(!isIndexProviderReady\(key\)\) return false;/, 'HUD search should filter unsupported provider indexes');
assert.match(app, /function getActiveConfig\(\)/, 'app should expose active config resolver');
assert.match(app, /requestedProvider === 'sentinelhub'[\s\S]*merged\.IMAGE_PROVIDER = internalAppConfig\.IMAGE_PROVIDER/, 'app should force the internal provider unless Sentinel fallback is explicitly allowed');
assert.match(app, /sentinelFeatureUnavailable\('AOI history scan'\)/, 'AOI scan should be paused under GEE default');
assert.match(app, /sentinelFeatureUnavailable\('Report generation'\)/, 'report generation should be paused under GEE default');
assert.doesNotMatch(app, /getWMSLayer/, 'app shell should use provider-neutral index layers');
assert.match(map, /export function getImageryProvider/, 'map provider helper should be exported');
assert.match(map, /ALLOW_SENTINEL_FALLBACK !== true[\s\S]*return 'cog'/, 'map provider helper should ignore Sentinel Hub unless fallback is explicit');
assert.match(map, /export function getCOGLayer/, 'map should provide a COG tile layer');
assert.match(map, /\/api\/cog\/tiles/, 'map should route COG tiles to the COG endpoint');
assert.match(map, /Public Sentinel-2 COGs \/ Element84 Earth Search/, 'COG attribution should be visible on tiles');
assert.match(map, /export function getGEELayer/, 'map should provide a GEE tile layer');
assert.match(map, /\/api\/gee\/tiles/, 'map should keep the GEE endpoint available');
assert.match(map, /Google Earth Engine \/ Copernicus Sentinel-2/, 'GEE attribution should be visible on tiles');
assert.match(map, /const RateLimitedTile = L\.TileLayer\.extend/, 'Produced Water GEE tiles should use a fetch-based rate-limited tile layer');
assert.match(map, /maxConcurrent:\s*2/, 'Produced Water GEE tiles should limit concurrent browser fetches');
assert.match(map, /detectRetina:\s*true/, 'Produced Water GEE tiles should request sharper retina tiles on high-DPI displays');
assert.match(atlasApp, /requestedProvider === 'cog' && !cfg\.ATLAS_IMAGE_PROVIDER && !runtimeAtlasImageProviderOverride[\s\S]*\? 'gee'[\s\S]*: requestedProvider/, 'Atlas should normalize global COG default to GEE until Atlas formulas are ported');
assert.match(atlasApp, /runtimeAtlasImageProviderOverride = 'sentinelhub'/, 'Atlas Sentinel HUD switch should route the session to Sentinel Hub');
assert.match(atlasApp, /runtimeAtlasImageProviderOverride === 'sentinelhub'[\s\S]*runtimeAtlasImageProviderOverride = null/, 'Atlas Sentinel HUD switch should restore the default provider when switched off');
assert.match(atlasApp, /ALLOW_SENTINEL_FALLBACK === true/, 'Atlas should keep configured Sentinel fallback locked unless explicitly allowed');
assert.match(atlasApp, /function getAtlasSentinelGuardStatus/, 'Atlas should guard Sentinel WMS by armed state and zoom');
assert.match(atlasApp, /function extractProviderErrorMessage/, 'Atlas should parse provider error bodies for visible tile status');
assert.match(atlasApp, /isQuotaExhausted/, 'Atlas should classify Sentinel Hub quota/credit 403 responses');
assert.match(atlasApp, /atlas-toggle-sentinel-live/, 'Atlas should wire a visible Sentinel live-tile switch');
assert.match(atlasApp, /atlas-sentinel-min-zoom/, 'Atlas should wire a visible Sentinel minimum zoom slider');
assert.match(atlasApp, /function getRetryAfterMs/, 'Atlas Sentinel WMS loader should honor Retry-After cooldowns');
assert.match(atlasApp, /tileSize:\s*512/, 'Atlas Sentinel WMS tiles should use larger tiles to reduce request count');
assert.match(atlasApp, /maxConcurrent:\s*1/, 'Atlas Sentinel WMS should avoid bursty parallel requests');
assert.match(atlasApp, /setAtlasSentinelWmsCooldown/, 'Atlas Sentinel WMS should maintain rate-limit cooldown state');
assert.match(atlasApp, /function applyGEE/, 'Atlas should provide a GEE tile renderer');
assert.match(atlasApp, /app: 'atlas'/, 'Atlas GEE tiles should identify the Atlas app namespace');
assert.match(atlasApp, /this\._maxConcurrent = options\.maxConcurrent \|\| 2/, 'Atlas GEE tiles should queue fetches instead of bursting all tiles');
assert.match(atlasApp, /detectRetina:\s*true/, 'Atlas GEE tiles should request sharper retina tiles on high-DPI displays');
assert.match(atlasApp, /applyAtlasTiles\(idx, bm\.date\)/, 'Atlas selection should use provider-neutral rendering');
assert.match(atlasApp, /applyWMS\(getDisplayEvalscript\(idx\), date, opts\)/, 'Atlas Sentinel fallback should remain explicit');
assert.match(server, /GEE_MAP_NAME_\$\{safeApp\}_\$\{safeIndex\}/, 'GEE server should support app-scoped map names');
assert.match(server, /@google\/earthengine/, 'GEE server should use the official Earth Engine client');
assert.match(server, /import 'dotenv\/config'/, 'GEE server should load local .env values');
assert.match(server, /COPERNICUS\/S2_SR_HARMONIZED/, 'GEE server should use Sentinel-2 SR Harmonized by default');
assert.match(server, /function buildIndexImage/, 'GEE server should build dynamic index images');
assert.match(server, /getMapId/, 'GEE server should create Earth Engine map IDs dynamically');
assert.match(server, /const tileResponseCache = new Map\(\)/, 'GEE server should cache successful tile byte responses');
assert.match(server, /const inFlightTileResponses = new Map\(\)/, 'GEE server should dedupe simultaneous identical tile requests');
assert.match(server, /TILE_FETCH_MAX_CONCURRENT/, 'GEE server should limit outbound Earth Engine tile fetches');
assert.match(server, /tileResp\.status !== 429/, 'GEE server should retry upstream 429 tile responses');
assert.match(server, /GEE_SINGLE_DATE_LOOKBACK_DAYS/, 'GEE server should expand single-date S2 requests to a lookback window');
assert.match(server, /GEE_SINGLE_DATE_FORWARD_DAYS/, 'GEE server should expand single-date S2 requests to a forward window');
assert.match(server, /const maxcc = Number\(searchParams\.get\('maxcc'\) \|\| 90\)/, 'GEE server should use cloud-tolerant default S2 filtering');
assert.match(server, /Browser API keys alone cannot create Earth Engine maps/, 'GEE server should reject API-key-only setup clearly');
assert.match(server, /\/api\/cog\/tiles\//, 'local server should expose COG tile endpoint');
assert.match(server, /\/api\/cog\/prewarm/, 'local server should expose a COG prewarm endpoint');
assert.match(server, /COG_SUPPORTED_INDEXES = new Set\(\['tc', 'truecolor', 'true-color', 'pwi', 'hpwi', 'pwoi', 'lbi'\]\)/, 'COG server should fail closed on unsupported indexes');
assert.match(server, /COG_PREWARM_ON_START/, 'COG server should support startup prewarm for demos');
assert.match(server, /function prewarmCogTargets/, 'COG server should prewarm demo target tiles');
assert.match(server, /execution\/render_cog_tile\.py/, 'local server should delegate COG rendering to deterministic execution script');
assert.match(server, /COG_TILE_CACHE_DIR/, 'local server should cache COG tiles on disk');
assert.match(server, /COG_RENDER_VERSION/, 'COG tile cache keys should include renderer versioning');
assert.match(server, /COG_ITEM_CACHE_DIR/, 'local server should pass an item-selection cache to the COG renderer');
assert.match(cogRenderer, /if index_key not in INDEX_BANDS/, 'COG renderer should reject unsupported index keys deterministically');
assert.match(cogRenderer, /Unsupported COG index/, 'COG renderer should name unsupported index failures clearly');
assert.match(cogRenderer, /item_cache_key/, 'COG renderer should cache STAC item selection across index requests');
assert.match(cogRenderer, /alpha = np\.where\(\(score >= threshold\) & valid, 70 \+ ramp \* 165, 0\)/, 'COG overlays should use graded sparse alpha instead of opaque masks');
assert.match(smoke, /urlPath\.startsWith\('\/api\/gee\/tiles\/'\)/, 'browser smoke test should stub local GEE tiles');
assert.match(shareHtml, /index\.html\?share=sentinel-only/, 'share entrypoint should route to Sentinel-only mode');

console.log('Imagery provider contract OK');
